### ISSUE TITLE
Why are you releasing a virus to public?

### ISSUE THREAD

**Issue by realPiyush** [hawksh/Hidden-miner-builder#13]
Github is for sharing code and helping the community if you released the source I would have complained less but here you are distributing a prebuilt binary that can be used as a virus and believe me it is being used as virus. I highly recommend you that you take down the repository.

**Comment by Rafo124** [comment]
Shut up loser

**Comment by joldboy69** [comment]
Well, if you read the README.md file it CLEARLY SAYS "A responsibility: The Developer shall not be liable for any damage, direct or indirect damages (including losses from loss of profit, loss of commercial information, etc.) of property or other nature, associated with the use or impossibility of using the Software Product." Next time, please read the documentation first

**Comment by real-Piyush-Sharma** [comment]
@joldboy69 Do you seriously think anybody whose intentions are malicious cares what does the read me says? I don't think that anyone who wants to embed this in an app cares about anything other than downloading the binary.

**Comment by Incog-Makes** [comment]
@real-Piyush-Sharma many people make things that can be used for malware. Be it open source botnet projects, keyloggers or ransomware, they're made for educational purposes to teach others, why should the makers not make them just because a small amount of people use it the wrong way

**Comment by realPiyush** [comment]
@Incog-Makes I understand what you mean, but the thing is that the repo owner is only releasing the pre compiled binary, I would have had no problem if the owner released the android compatible source code, but by releasing a pre compiled binary it makes a malicious persons job multiple times easier

**Comment by Rafo124** [comment]
> @Incog-Makes I understand what you mean, but the thing is that the repo owner is only releasing the pre compiled binary, I would have had no problem if the owner released the android compatible source code, but by releasing a pre compiled binary it makes a malicious persons job multiple times easier

None of your arguments make sense. Even if he didn't release a pre compiled version, they could have compiled it themselves. So stop being mad because you accidentally installed it yourself

**Comment by hawksh** [comment]
I understand your indignation. But this is only a tool, it is up to the end user to decide how to use it. The knife can also be used as a weapon or as a cooking tool. The project has detections and it is quite easy to use antivirus for protection.
