### ISSUE TITLE
i works but

### ISSUE THREAD

**Issue by Batuhan4** [hawksh/Hidden-miner-builder#3]
it works but i had 2 issues on win 7 32 bit
it mines but not for my pool or account idk but cpu usage was %90
and i selected %50 
i think there is a bug

**Comment by Nikitka12XD** [comment]
I myself noticed that miners do not pay attention to the limit and mine dynamically, depending on how much load. Because of this, users do not lag.

**Comment by Batuhan4** [comment]
users are lagging and after i removed  miner they are still lagging then i formatted the pc dont use this program

**Comment by hawksh** [comment]
> 
> 
> it works but i had 2 issues on win 7 32 bit
> it mines but not for my pool or account idk but cpu usage was %90
> and i selected %50
> i think there is a bug

Most likely due to a weak computer. Or, if the processor is single-core. But do not worry, the miner has a dynamic load.

**Comment by hawksh** [comment]
> 
> 
> users are lagging and after i removed miner they are still lagging then i formatted the pc dont use this program

I think you just didn’t figure it out completely ...
